// AI Factory — a concept map of patterns for building software with agent fleets
// (synthesized from a June-2026 research brief on "AI Factories for the SDLC").
//
// This is the ONLY file you need to edit to change what the graph shows.
// Each node: { id, label, category, description, stat?, sources?, notes?, connectsTo[] }
//   - category: one of CATEGORIES below (drives spatial clustering + the panel chip)
//   - stat:     short headline metric (optional)
//   - sources:  short citations (optional)
//   - notes:    quotable lines (optional)
// Links between nodes are derived from `connectsTo` automatically (see bottom).
// Node size scales with how connected a concept is.

// Ordered theme list — single source of truth for clustering and the panel chip.
export const CATEGORIES = [
  { id: 'production-line', label: 'Production Line', short: 'Production' },
  { id: 'patterns', label: 'Orchestration Patterns', short: 'Patterns' },
  { id: 'methods', label: 'Methodologies', short: 'Methods' },
  { id: 'parallelism', label: 'Parallelism', short: 'Parallelism' },
  { id: 'context-memory', label: 'Context & Memory', short: 'Context' },
  { id: 'memory', label: 'Memory & Retrieval', short: 'Memory' },
  { id: 'learning', label: 'Continual Learning', short: 'Learning' },
  { id: 'verification', label: 'Verification & Quality', short: 'Verification' },
  { id: 'governance', label: 'Governance & Security', short: 'Governance' },
  { id: 'cost-tokens', label: 'Cost & Tokens', short: 'Cost' },
  { id: 'tools', label: 'Tooling', short: 'Tooling' },
  { id: 'roles-org', label: 'Roles & Org', short: 'Roles' },
  { id: 'metrics', label: 'Metrics & Risk', short: 'Metrics' },
]

export const nodes = [
  // ── Production Line ─────────────────────────────────────────────
  {
    id: 'ai-factory',
    type: 'Practice',
    domain: 'Process',
    label: 'Running an AI Factory',
    category: 'production-line',
    description:
      "The operating model: running fleets of coding agents along a repeatable production line, where the human's job becomes specification, orchestration, and review — not typing.",
    connectsTo: ['production-line', 'orchestrator', 'spec-driven', 'verification-bottleneck', 'fleet-management'],
  },
  {
    id: 'production-line',
    type: 'Practice',
    domain: 'Process',
    label: 'Running the Production Line',
    category: 'production-line',
    description: 'The six-step line — Plan, Spawn, Monitor, Verify, Integrate, Retro — that maps factory discipline onto agentic development.',
    sources: ['Osmani, “The Code Agent Orchestra”'],
    connectsTo: ['ai-factory', 'plan-mode', 'wip-limits', 'retro', 'kill-criteria'],
  },
  {
    id: 'orchestrator',
    type: 'Principle',
    domain: 'Process',
    label: 'Orchestration beats conducting',
    category: 'production-line',
    description: 'The mindset shift from conductor (one agent, synchronous) to orchestrator (many agents, asynchronous).',
    connectsTo: ['orchestrator-worker', 'wip-limits', 'ai-factory'],
  },
  {
    id: 'kill-criteria',
    type: 'Practice',
    domain: 'Process',
    label: 'Killing Stuck Agents',
    category: 'production-line',
    description: 'If an agent is stuck 3+ iterations on the same error, stop it and reassign to a fresh agent.',
    connectsTo: ['ralph-loop', 'out-of-context-verification', 'production-line'],
  },
  {
    id: 'retro',
    type: 'Practice',
    domain: 'Process',
    label: 'Compounding Learning',
    category: 'production-line',
    description: 'Per-task retros that append learnings to a memory file so improvement compounds over time.',
    connectsTo: ['agents-md', 'middle-loop', 'production-line'],
  },

  // ── Orchestration Patterns ──────────────────────────────────────
  {
    id: 'orchestrator-worker',
    type: 'Practice',
    domain: 'Patterns',
    label: 'Orchestrating Workers',
    category: 'patterns',
    description: 'A lead agent decomposes work and delegates to specialist sub-agents working in parallel on a shared filesystem.',
    stat: '+90.2% vs single-agent · ~15× tokens',
    sources: ['Anthropic'],
    connectsTo: ['hierarchical-subagents', 'orchestrator', 'agent-teams', 'ai-factory'],
  },
  {
    id: 'hierarchical-subagents',
    type: 'Practice',
    domain: 'Patterns',
    label: 'Spawning Subagent Hierarchies',
    category: 'patterns',
    description: "Feature-lead agents that spawn their own specialists — deeper decomposition without blowing up the orchestrator's context.",
    connectsTo: ['orchestrator-worker', 'context-engineering'],
  },
  {
    id: 'plan-mode',
    type: 'Practice',
    domain: 'Patterns',
    label: 'Plan Mode',
    category: 'patterns',
    description: 'The agent presents a structured plan (files, changes, sequence) for human approval before executing.',
    notes: ['It is far cheaper to fix a bad plan than to fix bad code.'],
    connectsTo: ['plan-approval', 'spec-driven', 'rubber-duck', 'production-line'],
  },
  {
    id: 'plan-approval',
    type: 'Practice',
    domain: 'Patterns',
    label: 'Plan Approval',
    category: 'patterns',
    description: 'A human gate on the plan before any code is written — the feature that makes autonomy trustworthy.',
    connectsTo: ['plan-mode'],
  },
  {
    id: 'evaluator-optimizer',
    type: 'Practice',
    domain: 'Patterns',
    label: 'Evaluating then Optimizing',
    category: 'patterns',
    description: 'One agent generates, a separate agent critiques and refines — the verification loop made explicit.',
    connectsTo: ['separate-agent-verification', 'llm-as-judge', 'best-of-n'],
  },
  {
    id: 'best-of-n',
    type: 'Practice',
    domain: 'Patterns',
    label: 'Sampling Best-of-N',
    category: 'patterns',
    description: 'A cheap executor calls a stronger advisor model only on hard cases; generate N attempts and pick the best.',
    connectsTo: ['multi-model-routing', 'rubber-duck', 'evaluator-optimizer'],
  },
  {
    id: 'rubber-duck',
    type: 'Practice',
    domain: 'Patterns',
    label: 'Rubber-Ducking',
    category: 'patterns',
    description: 'A critic run after planning, after a complex implementation, and after writing tests but before running them.',
    connectsTo: ['plan-mode', 'verification-bottleneck', 'best-of-n'],
  },
  {
    id: 'ralph-loop',
    type: 'Practice',
    domain: 'Patterns',
    label: 'Running the Ralph Loop',
    category: 'patterns',
    description: 'Break work into atomic tasks and loop an agent — pick, implement, validate, commit, reset context — using compile + tests as the halting condition.',
    notes: ['Ship while you sleep.'],
    sources: ['Huntley', 'Carson'],
    connectsTo: ['out-of-context-verification', 'progress-files', 'kill-criteria', 'fleet-management'],
  },

  // ── Methodologies ───────────────────────────────────────────────
  {
    id: 'spec-driven',
    type: 'Practice',
    domain: 'Process',
    label: 'Writing Specs First',
    category: 'methods',
    description: 'Specs as version-controlled, executable contracts that constrain agent output — the defining methodology of 2026.',
    notes: ['The spec is the prompt.'],
    sources: ['GitHub Spec Kit', 'Fowler'],
    connectsTo: ['spec-as-contract', 'plan-mode', 'eval-driven', 'ai-factory'],
  },
  {
    id: 'spec-as-contract',
    type: 'Principle',
    domain: 'Process',
    label: 'The spec is the contract',
    category: 'methods',
    description: 'Intent is the source of truth; code is the regenerable output of a precise specification.',
    connectsTo: ['spec-driven', 'verification-bottleneck'],
  },
  {
    id: 'test-driven',
    type: 'Practice',
    domain: 'Process',
    label: 'Writing Tests First',
    category: 'methods',
    description: "Writing tests before code so agents can't generate tests that merely confirm their own broken output.",
    connectsTo: ['eval-driven', 'deterministic-verifiers'],
  },
  {
    id: 'eval-driven',
    type: 'Practice',
    domain: 'Process',
    label: 'Defining Evals First',
    category: 'methods',
    description: 'Define capabilities and held-out eval sets before building the agent; combine deterministic checks, LLM-as-judge, and human review.',
    sources: ['Inspect AI', 'Braintrust'],
    connectsTo: ['test-driven', 'llm-as-judge', 'spec-driven'],
  },
  {
    id: 'fleet-management',
    type: 'Practice',
    domain: 'Process',
    label: 'Managing Agent Fleets',
    category: 'methods',
    description: 'Engineers trigger autonomous changes; agents write, test, and build in sandboxes and open PRs — resting on a catalog of every component and its owner.',
    stat: '650+ agent PRs/mo · up to 90% time saved',
    notes: ["You can't safely automate what you don't understand."],
    sources: ['Spotify “Honk”'],
    connectsTo: ['ai-factory', 'sandboxing', 'quality-gates', 'ralph-loop', 'cloud-agents'],
  },
  {
    id: 'middle-loop',
    type: 'Practice',
    domain: 'Process',
    label: 'Supervising the Middle Loop',
    category: 'methods',
    description: 'A new supervisory layer of engineering work emerging between the inner loop (coding) and the outer loop (delivery).',
    sources: ['ThoughtWorks'],
    connectsTo: ['review-capacity', 'roles-shift', 'retro'],
  },

  // ── Parallelism ─────────────────────────────────────────────────
  {
    id: 'worktree-isolation',
    type: 'Practice',
    domain: 'Patterns',
    label: 'Isolating Worktrees',
    category: 'parallelism',
    description: 'Git worktrees give each agent its own working directory and branch over one .git store, moving conflicts to merge time.',
    stat: '~3× tokens for 3 agents',
    connectsTo: ['wip-limits', 'one-file-one-owner', 'integration-branch', 'token-engineering'],
  },
  {
    id: 'integration-branch',
    type: 'Practice',
    domain: 'Patterns',
    label: 'Merging via Integration Branch',
    category: 'parallelism',
    description: 'Merge agent output to a staging branch, run tests, then merge clean to main.',
    connectsTo: ['worktree-isolation', 'quality-gates'],
  },
  {
    id: 'wip-limits',
    type: 'Practice',
    domain: 'Patterns',
    label: 'Limiting WIP (3–5)',
    category: 'parallelism',
    description: "Don't run more agents than you can review; 3–5 is the repeatedly cited sweet spot.",
    stat: 'sweet spot: 3–5 agents',
    connectsTo: ['one-file-one-owner', 'worktree-isolation', 'review-capacity'],
  },
  {
    id: 'one-file-one-owner',
    type: 'Principle',
    domain: 'Patterns',
    label: 'Each file must have one owner',
    category: 'parallelism',
    description: 'Never let two agents edit the same file at once.',
    connectsTo: ['worktree-isolation', 'wip-limits'],
  },

  // ── Context & Memory ────────────────────────────────────────────
  {
    id: 'context-engineering',
    type: 'Practice',
    domain: 'Memory',
    label: 'Context Engineering',
    category: 'context-memory',
    description: 'Engineering what goes into the context window — not just the prompt — is now the core discipline.',
    connectsTo: ['context-rot', 'agents-md', 'initializer-agent', 'hierarchical-subagents'],
  },
  {
    id: 'context-rot',
    type: 'Problem',
    domain: 'Memory',
    label: 'Context Rot',
    category: 'context-memory',
    description: 'Every model degrades as the window fills with the wrong tokens; bigger windows shift the problem, not solve it.',
    sources: ['Chroma'],
    connectsTo: ['context-engineering'],
  },
  {
    id: 'agents-md',
    type: 'Tool',
    domain: 'Memory',
    label: 'AGENTS.md',
    category: 'context-memory',
    description: 'A human-curated memory file of project rules and learnings that bridges context resets.',
    stat: 'dev-written +4% · AI-generated ~−3%, +20% cost',
    sources: ['Gloaguen et al., ETH Zurich'],
    connectsTo: ['retro', 'context-engineering'],
  },
  {
    id: 'initializer-agent',
    type: 'Role',
    domain: 'Memory',
    label: 'Initializer Agent',
    category: 'context-memory',
    description: 'On first run, sets up the environment and writes a comprehensive requirements file for later sessions.',
    connectsTo: ['progress-files', 'context-engineering'],
  },
  {
    id: 'progress-files',
    type: 'Tool',
    domain: 'Memory',
    label: 'Progress Files',
    category: 'context-memory',
    description: "Artifacts like claude-progress.txt that let agents work 'in shifts,' carrying state across context resets.",
    connectsTo: ['initializer-agent', 'ralph-loop'],
  },

  // ── Verification & Quality ──────────────────────────────────────
  {
    id: 'verification-bottleneck',
    type: 'Problem',
    domain: 'Verification',
    label: 'Verification Bottleneck',
    category: 'verification',
    description: 'The binding constraint has shifted decisively from code generation to verification.',
    notes: ['The bottleneck is no longer typing — it is review.'],
    connectsTo: ['separate-agent-verification', 'quality-gates', 'acceleration-whiplash', 'ai-factory', 'rubber-duck', 'spec-as-contract'],
  },
  {
    id: 'separate-agent-verification',
    type: 'Practice',
    domain: 'Verification',
    label: 'Verifying with a Separate Agent',
    category: 'verification',
    description: "A different model or fresh-context agent verifies, because a model grading its own work shares its own blind spots.",
    notes: ['Never let the writer grade its own exam.'],
    connectsTo: ['llm-as-judge', 'evaluator-optimizer', 'verification-bottleneck'],
  },
  {
    id: 'llm-as-judge',
    type: 'Practice',
    domain: 'Verification',
    label: 'Judging with an LLM',
    category: 'verification',
    description: 'An LLM compares the diff against the original prompt to catch over-ambitious agents that drift outside their brief.',
    sources: ['Spotify “Honk”'],
    connectsTo: ['eval-driven', 'separate-agent-verification', 'deterministic-verifiers'],
  },
  {
    id: 'quality-gates',
    type: 'Practice',
    domain: 'Verification',
    label: 'Running Quality Gates',
    category: 'verification',
    description: 'Hooks that run lint/build/test on task completion and block an agent from stopping on red.',
    connectsTo: ['deterministic-verifiers', 'fleet-management', 'integration-branch'],
  },
  {
    id: 'deterministic-verifiers',
    type: 'Tool',
    domain: 'Verification',
    label: 'Deterministic Verifiers',
    category: 'verification',
    description: 'Non-LLM checks — format, build, test — that give an objective halting signal.',
    connectsTo: ['quality-gates', 'out-of-context-verification', 'test-driven'],
  },
  {
    id: 'out-of-context-verification',
    type: 'Practice',
    domain: 'Verification',
    label: 'Verifying Out of Context',
    category: 'verification',
    description: "Using compile + tests outside the agent's context as the halting condition solves the 'all done, tests pass!' lying problem.",
    connectsTo: ['ralph-loop', 'deterministic-verifiers', 'kill-criteria'],
  },

  // ── Governance & Security ───────────────────────────────────────
  {
    id: 'sandboxing',
    type: 'Practice',
    domain: 'Governance',
    label: 'Sandboxing',
    category: 'governance',
    description: "Isolated execution (microVMs/gVisor) that can't stop prompt injection but contains its blast radius.",
    connectsTo: ['defense-in-depth', 'fleet-management', 'containment'],
  },
  {
    id: 'owasp-agentic',
    type: 'Tool',
    domain: 'Governance',
    label: 'OWASP Agentic Top 10',
    category: 'governance',
    description: 'The OWASP Top 10 for Agentic Applications; Agent Goal Hijacking (ASI01) ranks #1.',
    sources: ['OWASP 2025'],
    connectsTo: ['defense-in-depth', 'containment'],
  },
  {
    id: 'defense-in-depth',
    type: 'Principle',
    domain: 'Governance',
    label: 'Security needs layered defenses',
    category: 'governance',
    description: 'Scoped read-only tokens, secrets kept out of the agent, egress firewalls, safe-output gates, threat scans.',
    connectsTo: ['sandboxing', 'governance-as-code', 'owasp-agentic'],
  },
  {
    id: 'containment',
    type: 'Principle',
    domain: 'Governance',
    label: 'Containment beats prevention',
    category: 'governance',
    description: 'Assume prompt injection will happen; design proportional human approval gates instead of trying to prevent it.',
    connectsTo: ['sandboxing', 'owasp-agentic'],
  },
  {
    id: 'governance-as-code',
    type: 'Practice',
    domain: 'Governance',
    label: 'Codifying Governance',
    category: 'governance',
    description: 'Codify the security pipeline — token scope, sandbox, firewall, safe-outputs, scan — as part of the workflow.',
    connectsTo: ['defense-in-depth', 'quality-gates'],
  },

  // ── Cost & Tokens ───────────────────────────────────────────────
  {
    id: 'token-engineering',
    type: 'Practice',
    domain: 'Cost',
    label: 'Budgeting Tokens',
    category: 'cost-tokens',
    description: 'Treat tokens as a budget: prune unused tools, replace MCP calls with deterministic CLI calls, run auditor/optimizer agents.',
    stat: '−62% token spend',
    sources: ['GitHub'],
    connectsTo: ['prompt-cache', 'mcp-pruning', 'worktree-isolation', 'multi-model-routing'],
  },
  {
    id: 'prompt-cache',
    type: 'Practice',
    domain: 'Cost',
    label: 'Tracking Cache Hit Rate',
    category: 'cost-tokens',
    description: 'High cache hit rates separate cheap from ruinous; a sudden drop signals a prompt-assembly bug.',
    stat: 'target >94% · ~70% = bug',
    sources: ['GitHub'],
    connectsTo: ['token-engineering'],
  },
  {
    id: 'mcp-pruning',
    type: 'Practice',
    domain: 'Cost',
    label: 'MCP Tool Pruning',
    category: 'cost-tokens',
    description: "A 40-tool MCP server can add 10–15 KB of schema per turn; drop the tools the agent doesn't use.",
    sources: ['GitHub'],
    connectsTo: ['token-engineering'],
  },
  {
    id: 'multi-model-routing',
    type: 'Practice',
    domain: 'Cost',
    label: 'Multi-Model Routing',
    category: 'cost-tokens',
    description: 'Cheap models for planning, strong models for implementation, a separate model for review.',
    stat: 'Haiku 0.25× · Sonnet 1× · Opus 5×',
    connectsTo: ['best-of-n', 'token-engineering'],
  },

  // ── Tooling ─────────────────────────────────────────────────────
  {
    id: 'agent-teams',
    type: 'Tool',
    domain: 'Tooling',
    label: 'Agent Teams (Tier 1)',
    category: 'tools',
    description: 'In-process subagents: a lead plus 3–5 teammates with a shared task list, dependency auto-unblock, and file locking.',
    connectsTo: ['orchestrator-worker', 'harness-race', 'local-orchestrators'],
  },
  {
    id: 'local-orchestrators',
    type: 'Tool',
    domain: 'Tooling',
    label: 'Local Orchestrators (Tier 2)',
    category: 'tools',
    description: 'Local tools (Conductor, Vibe Kanban, Cursor agents, Claude Squad) that run parallel sprints over worktrees.',
    connectsTo: ['worktree-isolation', 'agent-teams', 'cloud-agents'],
  },
  {
    id: 'cloud-agents',
    type: 'Tool',
    domain: 'Tooling',
    label: 'Cloud Async Agents (Tier 3)',
    category: 'tools',
    description: 'Cloud async agents (Claude Code Web, Copilot Coding Agent, Jules, Codex Web) that drain the backlog overnight.',
    connectsTo: ['fleet-management', 'local-orchestrators'],
  },
  {
    id: 'harness-race',
    type: 'Principle',
    domain: 'Tooling',
    label: 'The harness beats the model',
    category: 'tools',
    description: 'The frontier has moved from the model race to the harness race — the scaffolding around the model now matters most.',
    stat: 'SWE-bench 62% → 87% in ~1 yr',
    sources: ['Anthropic'],
    connectsTo: ['agent-teams'],
  },

  // ── Roles & Org ─────────────────────────────────────────────────
  {
    id: 'roles-shift',
    type: 'Principle',
    domain: 'Roles',
    label: 'Rigor must move upstream',
    category: 'roles-org',
    description: "Engineering rigor doesn't disappear — it moves upstream to specs, architecture, and review.",
    connectsTo: ['not-trusting-ai', 'junior-pipeline', 'middle-loop', 'review-capacity'],
  },
  {
    id: 'not-trusting-ai',
    type: 'Practice',
    domain: 'Roles',
    label: 'Not Trusting AI Code',
    category: 'roles-org',
    description: 'The new core skill: specifying precisely and reviewing rigorously rather than trusting AI output.',
    notes: ['Never file a PR with code you haven’t reviewed yourself.'],
    sources: ['Pragmatic Engineer 2026'],
    connectsTo: ['verification-bottleneck', 'review-capacity', 'roles-shift'],
  },
  {
    id: 'junior-pipeline',
    type: 'Problem',
    domain: 'Roles',
    label: 'Junior-Pipeline Debate',
    category: 'roles-org',
    description: 'AI adoption is pressuring entry-level hiring, risking a future mid-level talent gap and eroded mentorship.',
    stat: 'junior dev employment −9–10%',
    sources: ['Harvard 2026'],
    connectsTo: ['roles-shift'],
  },
  {
    id: 'conways-agents',
    type: 'Principle',
    domain: 'Roles',
    label: 'Agent topology amplifies org dysfunction',
    category: 'roles-org',
    description: 'Agent topologies can mirror dysfunctional org boundaries, reintroducing communication bottlenecks.',
    sources: ['ThoughtWorks'],
    connectsTo: ['orchestrator-worker', 'roles-shift'],
  },
  {
    id: 'circuit-breaker',
    type: 'Practice',
    domain: 'Roles',
    label: 'Predicting Risky PRs',
    category: 'roles-org',
    description: "Predict high-maintenance agent PRs at creation time, before they impose a hidden 'attention tax' on reviewers.",
    stat: '33,707 PRs · 28.3% merge instantly',
    sources: ["MSR '26"],
    connectsTo: ['no-review-merges', 'review-capacity'],
  },
  {
    id: 'review-capacity',
    type: 'Problem',
    domain: 'Roles',
    label: 'Review Capacity',
    category: 'roles-org',
    description: 'Review throughput is the scarce resource; add agents only as fast as you can review their output.',
    connectsTo: ['verification-bottleneck', 'acceleration-whiplash', 'not-trusting-ai'],
  },

  // ── Metrics & Risk ──────────────────────────────────────────────
  {
    id: 'acceleration-whiplash',
    type: 'Problem',
    domain: 'Verification',
    label: 'Acceleration Whiplash',
    category: 'metrics',
    description: 'Real throughput gains at the top, compounding quality costs at every stage below.',
    stat: 'epics +66% · bugs +54% · review +442% · no-review +31%',
    sources: ['Faros AI 2026'],
    connectsTo: ['faros', 'dora', 'verification-bottleneck', 'review-capacity'],
  },
  {
    id: 'faros',
    type: 'Tool',
    domain: 'Verification',
    label: 'Faros Telemetry',
    category: 'metrics',
    description: "Two years of telemetry quantifying AI's downside as well as its gains.",
    stat: '22,000+ devs · 4,000+ teams',
    sources: ['Faros AI 2026'],
    connectsTo: ['acceleration-whiplash', 'no-review-merges'],
  },
  {
    id: 'dora',
    type: 'Principle',
    domain: 'Verification',
    label: 'AI amplifies what already exists',
    category: 'metrics',
    description: 'AI magnifies the strengths of strong orgs and the dysfunctions of struggling ones.',
    notes: ['AI is an amplifier — it magnifies strengths and dysfunctions alike.'],
    sources: ['DORA 2025'],
    connectsTo: ['acceleration-whiplash', 'j-curve'],
  },
  {
    id: 'j-curve',
    type: 'Principle',
    domain: 'Verification',
    label: 'Productivity must dip before it rises',
    category: 'metrics',
    description: 'Value realization dips before it rises; expect an initial productivity drop.',
    sources: ['DORA 2026'],
    connectsTo: ['dora'],
  },
  {
    id: 'no-review-merges',
    type: 'Problem',
    domain: 'Verification',
    label: 'Unreviewed Merges',
    category: 'metrics',
    description: 'The clearest leading indicator of trouble: a creeping rate of PRs merged with no review at all.',
    stat: '+31.3% unreviewed merges',
    sources: ['Faros AI 2026'],
    connectsTo: ['faros', 'review-capacity', 'circuit-breaker'],
  },

  // ── Memory & Retrieval ──────────────────────────────────────────
  {
    id: 'vector-memory',
    type: 'Tool',
    domain: 'Memory',
    label: 'Vector Memory',
    category: 'memory',
    description: 'An HNSW-indexed vector store for semantic recall; degrades to a brute-force cosine scan when the native index is unavailable.',
    stat: 'HNSW: ~log-time vs O(n) scan',
    connectsTo: ['embeddings', 'hybrid-retrieval', 'mmr', 'context-engineering', 'graceful-degradation'],
  },
  {
    id: 'embeddings',
    type: 'Tool',
    domain: 'Memory',
    label: 'Sentence Embeddings',
    category: 'memory',
    description: 'Encode text into ~384-dim vectors for similarity search; a hash-based fallback runs without a model but carries no real semantics.',
    sources: ['all-MiniLM-L6-v2'],
    connectsTo: ['vector-memory', 'context-rot', 'reasoning-bank'],
  },
  {
    id: 'mmr',
    type: 'Practice',
    domain: 'Memory',
    label: 'Diversifying with MMR',
    category: 'memory',
    description: 'Maximal Marginal Relevance balances relevance against novelty so retrieved memories are not near-duplicates.',
    stat: 'λ·relevance + (1−λ)·novelty',
    connectsTo: ['vector-memory', 'reasoning-bank'],
  },
  {
    id: 'hybrid-retrieval',
    type: 'Practice',
    domain: 'Memory',
    label: 'Filtering Retrieval Candidates',
    category: 'memory',
    description: 'Combine vector similarity with structured metadata/time filters: over-fetch k×2 candidates, filter, then take the top-k.',
    connectsTo: ['vector-memory', 'memory-consolidation'],
  },
  {
    id: 'cross-session-memory',
    type: 'Practice',
    domain: 'Memory',
    label: 'Persisting Memory Across Sessions',
    category: 'memory',
    description: 'Serialize the vector store and its metadata to disk, then rehydrate on session start so agents remember across runs.',
    connectsTo: ['vector-memory', 'agents-md', 'progress-files'],
  },
  {
    id: 'memory-consolidation',
    type: 'Practice',
    domain: 'Memory',
    label: 'Consolidating Memory',
    category: 'memory',
    description: 'Housekeeping over stored memories: dedup near-identicals, flag contradictions, prune stale entries, and merge same-domain patterns.',
    connectsTo: ['vector-memory', 'reasoning-bank', 'pattern-learning'],
  },

  // ── Continual Learning ──────────────────────────────────────────
  {
    id: 'reasoning-bank',
    type: 'Tool',
    domain: 'Learning',
    label: 'Reasoning Bank',
    category: 'learning',
    description: 'Distill reusable strategies from past trajectories — retrieve, judge, distill, consolidate — then reapply them on new tasks.',
    notes: ['Retrieve → judge → distill → consolidate.'],
    connectsTo: ['trajectory-distillation', 'mmr', 'llm-as-judge', 'memory-consolidation', 'embeddings', 'eval-driven'],
  },
  {
    id: 'trajectory-distillation',
    type: 'Practice',
    domain: 'Learning',
    label: 'Distilling Trajectories',
    category: 'learning',
    description: 'Turn full run histories — actions, rewards, outcomes — into compact, reusable strategy memories.',
    connectsTo: ['reasoning-bank', 'continual-learning'],
  },
  {
    id: 'continual-learning',
    type: 'Practice',
    domain: 'Learning',
    label: 'Continual Learning',
    category: 'learning',
    description: "Update an agent's weights online from experience without retraining from scratch — or forgetting what it already knew.",
    connectsTo: ['micro-lora', 'ewc', 'fast-slow-weights', 'trajectory-distillation'],
  },
  {
    id: 'micro-lora',
    type: 'Tool',
    domain: 'Learning',
    label: 'Micro-LoRA',
    category: 'learning',
    description: 'Tiny low-rank adapters (rank 1–2) updated almost instantly to bias behavior toward recent feedback.',
    connectsTo: ['continual-learning', 'fast-slow-weights'],
  },
  {
    id: 'ewc',
    type: 'Practice',
    domain: 'Learning',
    label: 'Consolidating Elastic Weights',
    category: 'learning',
    description: 'Regularize updates to protect the weights that matter for old tasks — the standard guard against catastrophic forgetting.',
    connectsTo: ['continual-learning'],
  },
  {
    id: 'fast-slow-weights',
    type: 'Practice',
    domain: 'Learning',
    label: 'Balancing Dual-Speed Weights',
    category: 'learning',
    description: 'A fast adapter reacts immediately while a slower, larger one consolidates in the background — dual-speed adaptation.',
    connectsTo: ['continual-learning', 'micro-lora'],
  },
  {
    id: 'moe-routing',
    type: 'Practice',
    domain: 'Learning',
    label: 'MoE Agent Routing',
    category: 'learning',
    description: 'A learned gating network routes each task to the best expert agent via noisy top-k selection, updated online from reward.',
    stat: 'noisy top-k · load-balanced',
    connectsTo: ['multi-model-routing', 'orchestrator-worker', 'pattern-learning'],
  },
  {
    id: 'pattern-learning',
    type: 'Practice',
    domain: 'Learning',
    label: 'Pattern Learning',
    category: 'learning',
    description: 'Cluster recurring task/solution patterns and track a running success rate, surfacing the ones that keep working.',
    connectsTo: ['reasoning-bank', 'memory-consolidation', 'moe-routing'],
  },
  {
    id: 'graceful-degradation',
    type: 'Principle',
    domain: 'Learning',
    label: 'Fallbacks must be honest',
    category: 'learning',
    description: "When the heavy engine isn't installed, fall back to a transparent heuristic and report which path actually ran.",
    notes: ['Real engine or honest fallback — never a silent downgrade.'],
    connectsTo: ['vector-memory', 'embeddings'],
  },
]

// Relationship kind -> line style + default weight. Monochrome: the kind is
// encoded by line STYLE (solid/dashed/dotted), never colour; the legend reads
// the same grouping. Heavier weight => thicker line + tighter pull.
export const EDGE_TYPES = {
  enables: { style: 'solid', weight: 0.6 },
  requires: { style: 'solid', weight: 0.9 },
  feeds: { style: 'solid', weight: 0.5 },
  'part_of': { style: 'solid', weight: 0.8 },
  mitigates: { style: 'dashed', weight: 0.5 },
  tradeoff: { style: 'dashed', weight: 0.4 },
  measures: { style: 'dotted', weight: 0.4 },
  contradicts: { style: 'dotted', weight: 0.3 },
}

// Per-connection metadata, keyed by "a::b" (declared order; the derive checks
// both orders). `type` drives style + default weight; `description` shows in the
// panel; the hover label defaults to the type. Add `weight`/`style`/`label` to
// override. Edges with no entry render as a plain solid thin line.
export const EDGE_META = {
  'ai-factory::production-line': { type: 'part_of', description: 'The six-step line is the operating core of the factory.' },
  'ai-factory::orchestrator': { type: 'requires', description: 'Running a factory means orchestrating many agents, not conducting one.' },
  'ai-factory::spec-driven': { type: 'requires', description: 'Specs are the precise inputs every agent in the factory runs on.' },
  'ai-factory::verification-bottleneck': { type: 'tradeoff', description: 'Scaling the factory shifts the constraint onto verification.' },
  'ai-factory::fleet-management': { type: 'part_of', description: 'Fleet management is how a factory is run at scale.' },
  'production-line::plan-mode': { type: 'part_of', description: 'Plan is the first step of the production line.' },
  'production-line::wip-limits': { type: 'requires', description: 'The line only flows if work-in-progress stays reviewable.' },
  'production-line::retro': { type: 'part_of', description: 'Retro is the closing step that feeds learning back in.' },
  'production-line::kill-criteria': { type: 'requires', description: 'A reliable line needs explicit stop rules for stuck agents.' },
  'orchestrator::orchestrator-worker': { type: 'enables', description: 'Orchestration is realized through the orchestrator-worker pattern.' },
  'orchestrator::wip-limits': { type: 'requires', description: 'An orchestrator can only drive as many agents as can be reviewed.' },
  'kill-criteria::ralph-loop': { type: 'part_of', description: 'Stop rules are the halting condition of an iterative loop.' },
  'kill-criteria::out-of-context-verification': { type: 'requires', description: 'Knowing when to kill a run depends on external pass-fail signals.' },
  'retro::agents-md': { type: 'feeds', description: 'Retros append distilled learnings to the memory file.' },
  'retro::middle-loop': { type: 'part_of', description: 'Retros are part of the new supervisory middle loop.' },
  'orchestrator-worker::hierarchical-subagents': { type: 'enables', description: 'Workers can spawn their own specialists for deeper decomposition.' },
  'orchestrator-worker::agent-teams': { type: 'enables', description: 'Agent Teams implement orchestrator-worker in-process.' },
  'orchestrator-worker::ai-factory': { type: 'part_of', description: 'Orchestrator-worker is the factory core execution pattern.' },
  'hierarchical-subagents::context-engineering': { type: 'requires', description: 'Deep subagent trees only work with disciplined context budgets.' },
  'plan-mode::plan-approval': { type: 'requires', description: 'Plan mode is only useful with a human approval gate.' },
  'plan-mode::spec-driven': { type: 'feeds', description: 'A good spec is the input a plan is built from.' },
  'plan-mode::rubber-duck': { type: 'enables', description: 'Plans are sharpened by a post-planning critic pass.' },
  'evaluator-optimizer::separate-agent-verification': { type: 'requires', description: 'Evaluator-optimizer needs an independent verifier, not self-review.' },
  'evaluator-optimizer::llm-as-judge': { type: 'enables', description: 'An LLM judge can serve as the evaluator half of the loop.' },
  'evaluator-optimizer::best-of-n': { type: 'enables', description: 'Scoring N attempts is evaluator-optimizer in practice.' },
  'best-of-n::multi-model-routing': { type: 'requires', description: 'Best-of-N leans on routing cheap versus strong models per case.' },
  'best-of-n::rubber-duck': { type: 'enables', description: 'A critic can pick or refine among N candidate attempts.' },
  'rubber-duck::verification-bottleneck': { type: 'mitigates', description: 'Critic passes catch errors before they reach scarce review.' },
  'ralph-loop::out-of-context-verification': { type: 'requires', description: 'The loop halts on external compile and test signals.' },
  'ralph-loop::progress-files': { type: 'requires', description: 'The loop carries state across resets via progress files.' },
  'ralph-loop::fleet-management': { type: 'enables', description: 'Looping atomic tasks is what lets fleets run unattended.' },
  'spec-driven::spec-as-contract': { type: 'part_of', description: 'Treating the spec as a contract is the heart of SDD.' },
  'spec-driven::eval-driven': { type: 'enables', description: 'Specs define the criteria evals then check against.' },
  'spec-as-contract::verification-bottleneck': { type: 'mitigates', description: 'A precise contract gives verification an objective reference.' },
  'test-driven::eval-driven': { type: 'part_of', description: 'Test-first is the unit-level case of eval-driven development.' },
  'test-driven::deterministic-verifiers': { type: 'feeds', description: 'Tests are the deterministic checks an agent must pass.' },
  'eval-driven::llm-as-judge': { type: 'enables', description: 'Eval suites can use an LLM judge alongside hard checks.' },
  'fleet-management::sandboxing': { type: 'requires', description: 'Autonomous fleets must run inside sandboxes.' },
  'fleet-management::quality-gates': { type: 'requires', description: 'Fleet output only ships through automated quality gates.' },
  'fleet-management::cloud-agents': { type: 'enables', description: 'Cloud async agents are how fleets drain backlogs overnight.' },
  'middle-loop::review-capacity': { type: 'part_of', description: 'Managing review capacity is the substance of the middle loop.' },
  'middle-loop::roles-shift': { type: 'part_of', description: 'The middle loop is the new layer in the shifting engineer role.' },
  'worktree-isolation::wip-limits': { type: 'enables', description: 'Isolated worktrees are what make parallel WIP safe.' },
  'worktree-isolation::one-file-one-owner': { type: 'enables', description: 'Per-agent worktrees enforce single ownership of files.' },
  'worktree-isolation::integration-branch': { type: 'feeds', description: 'Isolated branches merge through an integration branch.' },
  'worktree-isolation::token-engineering': { type: 'tradeoff', description: 'More parallel worktrees burn proportionally more tokens.' },
  'integration-branch::quality-gates': { type: 'requires', description: 'Integration merges must pass the quality gates first.' },
  'wip-limits::one-file-one-owner': { type: 'requires', description: 'Bounded WIP pairs with one-owner-per-file to avoid clashes.' },
  'wip-limits::review-capacity': { type: 'requires', description: 'WIP limits are set by how much review capacity exists.' },
  'context-engineering::context-rot': { type: 'mitigates', description: 'Good context engineering is the defense against context rot.' },
  'context-engineering::agents-md': { type: 'part_of', description: 'A curated rules file is a core context-engineering artifact.' },
  'context-engineering::initializer-agent': { type: 'enables', description: 'An initializer agent sets up context for later sessions.' },
  'initializer-agent::progress-files': { type: 'feeds', description: 'The initializer writes the progress files later runs read.' },
  'verification-bottleneck::separate-agent-verification': { type: 'mitigates', description: 'A separate verifier widens the verification bottleneck.' },
  'verification-bottleneck::quality-gates': { type: 'mitigates', description: 'Automated gates absorb load off human verification.' },
  'verification-bottleneck::acceleration-whiplash': { type: 'feeds', description: 'An unaddressed verification gap is what tips into whiplash.' },
  'separate-agent-verification::llm-as-judge': { type: 'enables', description: 'An LLM judge is one way to run separate-agent verification.' },
  'llm-as-judge::deterministic-verifiers': { type: 'tradeoff', description: 'LLM judging trades objectivity for coverage versus hard checks.' },
  'quality-gates::deterministic-verifiers': { type: 'requires', description: 'Quality gates are built from deterministic checks.' },
  'deterministic-verifiers::out-of-context-verification': { type: 'part_of', description: 'Out-of-context checks are deterministic verifiers run externally.' },
  'sandboxing::defense-in-depth': { type: 'part_of', description: 'Sandboxing is one layer of defense-in-depth.' },
  'sandboxing::containment': { type: 'enables', description: 'Sandboxes contain blast radius rather than prevent attacks.' },
  'owasp-agentic::defense-in-depth': { type: 'feeds', description: 'The agentic threat list drives the defense-in-depth checklist.' },
  'owasp-agentic::containment': { type: 'mitigates', description: 'Containment is the practical answer to goal-hijacking risk.' },
  'defense-in-depth::governance-as-code': { type: 'enables', description: 'Defense-in-depth is codified as a governance pipeline.' },
  'governance-as-code::quality-gates': { type: 'part_of', description: 'Governance checks run as part of the quality gates.' },
  'token-engineering::prompt-cache': { type: 'requires', description: 'Token budgets live or die on prompt-cache hit rates.' },
  'token-engineering::mcp-pruning': { type: 'part_of', description: 'Pruning unused tools is a core token-engineering tactic.' },
  'token-engineering::multi-model-routing': { type: 'enables', description: 'Routing cheap versus strong models is a token-budget lever.' },
  'agent-teams::harness-race': { type: 'part_of', description: 'Agent Teams is a front in the harness race.' },
  'agent-teams::local-orchestrators': { type: 'tradeoff', description: 'In-process teams versus external orchestrators is a design choice.' },
  'local-orchestrators::worktree-isolation': { type: 'requires', description: 'Local orchestrators run agents in isolated worktrees.' },
  'local-orchestrators::cloud-agents': { type: 'tradeoff', description: 'Local parallel sprints versus cloud overnight runs.' },
  'roles-shift::not-trusting-ai': { type: 'enables', description: 'The shift upstream elevates reviewing over writing code.' },
  'roles-shift::junior-pipeline': { type: 'feeds', description: 'The shift upstream is what squeezes entry-level roles.' },
  'roles-shift::review-capacity': { type: 'requires', description: 'The new role centers on supplying review capacity.' },
  'not-trusting-ai::verification-bottleneck': { type: 'requires', description: 'Refusing to trust output is what makes verification the job.' },
  'not-trusting-ai::review-capacity': { type: 'requires', description: 'Reviewing rigorously consumes scarce review capacity.' },
  'conways-agents::orchestrator-worker': { type: 'tradeoff', description: 'Agent graphs risk re-encoding dysfunctional org boundaries.' },
  'conways-agents::roles-shift': { type: 'part_of', description: 'Agent topology is a dimension of the org and role shift.' },
  'circuit-breaker::no-review-merges': { type: 'mitigates', description: 'Circuit breakers catch the PRs that would merge unreviewed.' },
  'circuit-breaker::review-capacity': { type: 'mitigates', description: 'Predicting bad PRs protects scarce review capacity.' },
  'review-capacity::verification-bottleneck': { type: 'part_of', description: 'Review capacity is the human half of the verification bottleneck.' },
  'review-capacity::acceleration-whiplash': { type: 'mitigates', description: 'Adding review capacity is the brake on whiplash.' },
  'acceleration-whiplash::faros': { type: 'measures', description: 'Faros telemetry is what put numbers on the whiplash.' },
  'acceleration-whiplash::dora': { type: 'measures', description: 'DORA frames the whiplash as AI amplifying existing maturity.' },
  'faros::no-review-merges': { type: 'measures', description: 'Faros tracks the rise in unreviewed merges.' },
  'dora::j-curve': { type: 'part_of', description: 'The J-curve is part of the DORA value-realization model.' },
  'no-review-merges::review-capacity': { type: 'contradicts', description: 'Unreviewed merges are review capacity giving out.' },
  'vector-memory::embeddings': { type: 'requires', description: 'Vector memory indexes the embeddings text is encoded into.' },
  'vector-memory::hybrid-retrieval': { type: 'enables', description: 'Vector similarity is half of hybrid retrieval.' },
  'vector-memory::mmr': { type: 'feeds', description: 'MMR re-ranks the candidates vector memory returns.' },
  'vector-memory::context-engineering': { type: 'feeds', description: 'Retrieved memories are fed into the working context.' },
  'vector-memory::graceful-degradation': { type: 'tradeoff', description: 'Absent the native index, recall falls back to a slow scan.' },
  'embeddings::context-rot': { type: 'mitigates', description: 'Semantic retrieval helps fight irrelevant-context rot.' },
  'embeddings::reasoning-bank': { type: 'feeds', description: 'Embeddings let the bank find similar past trajectories.' },
  'mmr::reasoning-bank': { type: 'part_of', description: 'MMR diversity is the retrieval step of the reasoning bank.' },
  'hybrid-retrieval::memory-consolidation': { type: 'feeds', description: 'Filtered retrieval feeds what consolidation then prunes.' },
  'cross-session-memory::vector-memory': { type: 'requires', description: 'Cross-session memory serializes and reloads the vector store.' },
  'cross-session-memory::agents-md': { type: 'part_of', description: 'Both are mechanisms for memory that outlives a session.' },
  'cross-session-memory::progress-files': { type: 'part_of', description: 'Progress files are a lightweight form of cross-session memory.' },
  'memory-consolidation::vector-memory': { type: 'part_of', description: 'Consolidation is housekeeping over the vector store.' },
  'memory-consolidation::reasoning-bank': { type: 'part_of', description: 'Consolidate is the final step of the reasoning bank.' },
  'memory-consolidation::pattern-learning': { type: 'feeds', description: 'Consolidated memories surface the patterns worth keeping.' },
  'reasoning-bank::trajectory-distillation': { type: 'requires', description: 'The bank is built by distilling past trajectories.' },
  'reasoning-bank::llm-as-judge': { type: 'requires', description: 'The judge step scores trajectories before they are stored.' },
  'reasoning-bank::eval-driven': { type: 'enables', description: 'Stored strategies can seed evaluation criteria.' },
  'trajectory-distillation::continual-learning': { type: 'feeds', description: 'Distilled trajectories are the signal continual learning trains on.' },
  'continual-learning::micro-lora': { type: 'part_of', description: 'Micro-LoRA is the fast-update mechanism of continual learning.' },
  'continual-learning::ewc': { type: 'requires', description: 'Continual learning needs EWC to avoid catastrophic forgetting.' },
  'continual-learning::fast-slow-weights': { type: 'part_of', description: 'Dual-speed weights are how continual learning balances stability.' },
  'micro-lora::fast-slow-weights': { type: 'part_of', description: 'Micro-LoRA is the fast half of a fast-slow weight scheme.' },
  'moe-routing::multi-model-routing': { type: 'part_of', description: 'Agent routing generalizes model routing to whole experts.' },
  'moe-routing::orchestrator-worker': { type: 'enables', description: 'A learned router decides which worker gets each task.' },
  'moe-routing::pattern-learning': { type: 'requires', description: 'The router learns task-to-expert patterns from reward.' },
  'pattern-learning::reasoning-bank': { type: 'part_of', description: 'Pattern learning is the recurring-strategy layer of the bank.' },
  'graceful-degradation::embeddings': { type: 'tradeoff', description: 'No model means embeddings fall back to meaningless hashes.' },
}

// --- derive links from connectsTo (dedupe a–b / b–a), attaching edge metadata ---
const ids = new Set(nodes.map((n) => n.id))
const seen = new Set()
export const links = []
for (const n of nodes) {
  for (const target of n.connectsTo || []) {
    if (!ids.has(target)) continue // skip dangling references
    const key = [n.id, target].sort().join('::')
    if (seen.has(key)) continue
    seen.add(key)
    const meta = EDGE_META[`${n.id}::${target}`] || EDGE_META[`${target}::${n.id}`] || {}
    const def = (meta.type && EDGE_TYPES[meta.type]) || {}
    links.push({
      source: n.id,
      target,
      type: meta.type || null,
      style: meta.style || def.style || 'solid',
      weight: meta.weight ?? def.weight ?? 0.4,
      description: meta.description || null,
      label: meta.label || meta.type || null,
    })
  }
}
